using Oculus.Platform.Models;
using OVR;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using Unity.VisualScripting;
using UnityEditor.PackageManager;
using UnityEngine;
using static OVRPlugin;
using static UnityEngine.UI.Image;

public class PlayerController : MonoBehaviour
{
    public float _threshold = 0.27f;
    [Header("æŒ‡ãƒ‘ãƒƒãƒãƒ³")] public bool on_fingerSnap = false;
    [Header("æŒ‡ãƒ‘ãƒƒãƒãƒ³ã§å‡ºã¦ãã‚‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")]public GameObject prefab_FingerSnap;

    [Header("æ‰‹éŠƒ")] public bool on_gun = false;
    [Header("å°„ç¨‹è·é›¢")] public float bulletRange = 100f;

    [Header("ã‚µãƒ³ãƒ€ãƒ¼")] public AudioClip thunderSE;
    [Header("éŠƒå¼¾éŸ³")]public AudioClip gunSE;

    public AudioSource audioSource;

    [SerializeField]
    private OVRSkeleton _oVRSkeleton; //ï¿½Eï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Íï¿½ï¿½ï¿½ï¿½ Boneï¿½ï¿½ï¿½
    [SerializeField]
    private OVRHand _oVRHand;

    private bool _isThumbStraight_old;
    private bool _isInsexStraight_old;
    private bool _isMiddleStraight_old;
    private bool _isRingStraight_old;
    private bool _isPinkyStraight_old;

    

    public Vector3 indexDirection;

    private void Start()
    {

        // ï¿½nï¿½ï¿½ï¿½hï¿½gï¿½ï¿½ï¿½bï¿½Lï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Aï¿½Ü‚ï¿½ï¿½Íƒnï¿½ï¿½ï¿½hï¿½gï¿½ï¿½ï¿½bï¿½Lï¿½ï¿½ï¿½Oï¿½ÌMï¿½pï¿½xï¿½ï¿½ï¿½á‚¯ï¿½ï¿½ÎŒï¿½ì“®ï¿½ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ß‚É–ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        if (!_oVRHand.IsTracked || _oVRHand.HandConfidence.Equals(OVRHand.TrackingConfidence.Low)) return;

        var isThumbStraight_old = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Thumb0, OVRSkeleton.BoneId.Hand_Thumb1, OVRSkeleton.BoneId.Hand_Thumb2, OVRSkeleton.BoneId.Hand_Thumb3, OVRSkeleton.BoneId.Hand_ThumbTip);
        var isIndexStraight_old = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Index1, OVRSkeleton.BoneId.Hand_Index2, OVRSkeleton.BoneId.Hand_Index3, OVRSkeleton.BoneId.Hand_IndexTip);
        var isMiddleStraight_old = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Middle1, OVRSkeleton.BoneId.Hand_Middle2, OVRSkeleton.BoneId.Hand_Middle3, OVRSkeleton.BoneId.Hand_MiddleTip);
        var isRingStraight_old = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Ring1, OVRSkeleton.BoneId.Hand_Ring2, OVRSkeleton.BoneId.Hand_Ring3, OVRSkeleton.BoneId.Hand_RingTip);
        var isPinkyStraight_old = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Pinky0, OVRSkeleton.BoneId.Hand_Pinky1, OVRSkeleton.BoneId.Hand_Pinky2, OVRSkeleton.BoneId.Hand_Pinky3, OVRSkeleton.BoneId.Hand_PinkyTip);
        
        audioSource = this.gameObject.GetComponent<AudioSource>();
    }

    /// <summary>
    /// ï¿½wï¿½è‚µï¿½ï¿½ï¿½Sï¿½Ä‚ï¿½BoneIDï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×‚ï¿½
    /// </summary>
    /// <param name="threshold">è‡’l 1ï¿½É‹ß‚ï¿½ï¿½Ù‚ÇŒï¿½ï¿½ï¿½ï¿½ï¿½</param>
    /// <param name="boneids"></param>
    /// <returns></returns>
    private bool IsStraight(float threshold, params OVRSkeleton.BoneId[] boneids)
    {
        if (boneids.Length < 3) return false;   //ï¿½ï¿½ï¿½×‚æ‚¤ï¿½ï¿½ï¿½È‚ï¿½
        Vector3? oldVec = null;
        var dot = 1.0f;
        for (var index = 0; index < boneids.Length - 1; index++)
        {
            var v = (_oVRSkeleton.Bones[(int)boneids[index + 1]].Transform.position - _oVRSkeleton.Bones[(int)boneids[index]].Transform.position).normalized;
            if (oldVec.HasValue)
            {
                dot *= Vector3.Dot(v, oldVec.Value); //ï¿½ï¿½ï¿½Ï‚Ì’lï¿½ğ‘æ‚µï¿½Ä‚ï¿½ï¿½ï¿½
            }
            oldVec = v;//ï¿½Ğ‚Æ‚Â‘Oï¿½Ìwï¿½xï¿½Nï¿½gï¿½ï¿½
        }
        return dot >= threshold; //ï¿½wï¿½è‚µï¿½ï¿½BoneIDï¿½Ì“ï¿½ï¿½Ï‚Ì‘ï¿½ï¿½æ‚ªè‡’lï¿½ğ’´‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ç’¼ï¿½ï¿½ï¿½Æ‚İ‚È‚ï¿½
    
    }

    private void Update()
    {
        // ï¿½nï¿½ï¿½ï¿½hï¿½gï¿½ï¿½ï¿½bï¿½Lï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Aï¿½Ü‚ï¿½ï¿½Íƒnï¿½ï¿½ï¿½hï¿½gï¿½ï¿½ï¿½bï¿½Lï¿½ï¿½ï¿½Oï¿½ÌMï¿½pï¿½xï¿½ï¿½ï¿½á‚¯ï¿½ï¿½ÎŒï¿½ì“®ï¿½ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ß‚É–ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        if (!_oVRHand.IsTracked || _oVRHand.HandConfidence.Equals(OVRHand.TrackingConfidence.Low)) return;

        var isThumbStraight = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Thumb0, OVRSkeleton.BoneId.Hand_Thumb1, OVRSkeleton.BoneId.Hand_Thumb2, OVRSkeleton.BoneId.Hand_Thumb3, OVRSkeleton.BoneId.Hand_ThumbTip);
        var isIndexStraight = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Index1, OVRSkeleton.BoneId.Hand_Index2, OVRSkeleton.BoneId.Hand_Index3, OVRSkeleton.BoneId.Hand_IndexTip);
        var isMiddleStraight = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Middle1, OVRSkeleton.BoneId.Hand_Middle2, OVRSkeleton.BoneId.Hand_Middle3, OVRSkeleton.BoneId.Hand_MiddleTip);
        var isRingStraight = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Ring1, OVRSkeleton.BoneId.Hand_Ring2, OVRSkeleton.BoneId.Hand_Ring3, OVRSkeleton.BoneId.Hand_RingTip);
        var isPinkyStraight = IsStraight(0.27f, OVRSkeleton.BoneId.Hand_Pinky0, OVRSkeleton.BoneId.Hand_Pinky1, OVRSkeleton.BoneId.Hand_Pinky2, OVRSkeleton.BoneId.Hand_Pinky3, OVRSkeleton.BoneId.Hand_PinkyTip);

        var indexTipPos = _oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_IndexTip].Transform.position;
        var index1Pos = _oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_Index1].Transform.position;
        
        float indexDirection_x = indexTipPos.x - index1Pos.x;
        float indexDirection_y = indexTipPos.y - index1Pos.y;
        float indexDirection_z = indexTipPos.z - index1Pos.z;

        indexDirection = new Vector3(indexDirection_x, indexDirection_y, indexDirection_z);
 

        //ï¿½wï¿½pï¿½bï¿½`ï¿½ï¿½
        if(on_fingerSnap)
        {
            if (_isMiddleStraight_old && !isMiddleStraight && isIndexStraight)
            {
                audioSource.PlayOneShot(thunderSE);
                // Instantiate(
                //     prefab_FingerSnap, //ï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½nï¿½u
                //     position: _oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_IndexTip].Transform.position, //ï¿½ï¿½ï¿½ï¿½ï¿½êŠï¿½Fï¿½lï¿½ï¿½ï¿½ï¿½ï¿½wï¿½Ìï¿½
                //     rotation: Quaternion.identity //ï¿½ï¿½]ï¿½È‚ï¿½
                // );
                Instantiate(
                    prefab_FingerSnap, //ï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½nï¿½u
                    position: _oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_IndexTip].Transform.position, //ï¿½ï¿½ï¿½ï¿½ï¿½êŠï¿½Fï¿½lï¿½ï¿½ï¿½ï¿½ï¿½wï¿½Ìï¿½
                    rotation: Quaternion.identity //ï¿½ï¿½]ï¿½È‚ï¿½
                );
            }
        }

        if(on_gun)
        {
            if(_isThumbStraight_old && !isThumbStraight && isIndexStraight && !isMiddleStraight && !isRingStraight && !isPinkyStraight)
            {
                audioSource.PlayOneShot(gunSE);
                Debug.DrawRay(_oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_IndexTip].Transform.position, indexDirection, UnityEngine.Color.red,100f, false);
                if (Physics.Raycast(_oVRSkeleton.Bones[(int)OVRSkeleton.BoneId.Hand_IndexTip].Transform.position, indexDirection, bulletRange))
                {

                }
            
            }
        }


        _isThumbStraight_old = isThumbStraight;
        _isInsexStraight_old = isIndexStraight;
        _isMiddleStraight_old = isMiddleStraight;
        _isRingStraight_old = isRingStraight;
        _isPinkyStraight_old = isPinkyStraight;
}
}
